spring:
  application:
    name: Crypto application
  config:
    import: "vault:"
  cloud:
    vault:
      uri: http://localhost:8200
      token: 00000000-0000-0000-0000-000000000000
      kv:
        backend: secret
        default-context: application
        enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 32768
      linger-ms: 5
      buffer-memory: 33554432
      retries: 1
      retry-backoff-ms: 1000
      acks: all
      delivery-timeout-ms: 3000
      request-timeout-ms: 2000
      max-block-ms: 1000
      properties:
        acks: all
        compression.type: snappy
        max.request.size: 1048576
        specific.avro.reader: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

coinbase:
  client-id: 'not-from-vault'
  client-secret: 'not-from-vault'
  redirect-uri: 'not-from-vault'
binance:
  client-id: 'not-from-vault'
  client-secret: 'not-from-vault'
  redirect-uri: 'not-from-vault'

logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG
    org.springframework.core.env: DEBUG

app:
  kafka:
    topics:
      market-events: market.crypto.binance.stream

resilience4j:
  circuitbreaker:
    instances:
      binance:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - java.io.IOException
          - com.binance.connector.client.exceptions.BinanceClientException
          - com.binance.connector.client.exceptions.BinanceConnectorException
          - com.binance.connector.client.exceptions.BinanceServerException
        ignoreExceptions:
          - java.lang.IllegalArgumentException
