spring:
  application:
    name: Crypto application
  config:
    import: "vault:"
  cloud:
    vault:
      uri: http://localhost:8200
      token: 00000000-0000-0000-0000-000000000000
      kv:
        backend: secret
        default-context: application
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

coinbase:
  client-id: 'from-vault'
  client-secret: 'from-vault'

logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG
    org.springframework.core.env: DEBUG
